import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hom from "@/components/Home.jsx"
import Menu from '@/components/menu.jsx'
import Products from '@/components/products'
import Section1 from '@/components/section1'
import Review from '@/components/review'
import Contact from '@/components/contact'
import Mwanted from '@/components/Mwanted'
import Section2 from '@/components/section2'
export default function Home() {
  return (
    <>
      <Head>
        <title>patisserie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Playfair+Display:wght@400;500;600;700&display=swap" rel="stylesheet" />

      </Head>
      <Hom />
      <Menu />
      <Products />
      <Section1 />
      <Review />
      <Mwanted />
      <Section2 />
      <Contact />
    </>
  )
}
